# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = backend/migrations

# template used to generate new migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters to copy to slug
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow empty/non-existent migrations to run
# when executing 'upgrade'
# upgrade_token_auth = false

# sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/san_ai_db

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts. See the documentation for details.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
